#!/usr/bin/env bash

file_path="$1"

if [[ -f "$file_path" ]]; then
    echo "file '$file_path' exists"
    # nested if 
    if [[ ! -x "$file_path" ]]; then
        echo "file '$file_path' not executable"
    else
        echo "file '$file_path' executable"
    fi
else
    echo "file '$file_path' not exists"
    exit 1
fi

echo "program continues here ..."
