#!/usr/bin/env bash

script_path="$(readlink -f "$BASH_SOURCE")"
script_dir="$(dirname "$script_path")"

source "$script_dir/.env"

file="$1"

[[ -f "$file" ]] || { echo "file not found: $file" >&2; exit 1; }

podman exec -i oracle-free sqlplus -s system/"$ORACLE_PWD@FREEPDB1" < "$file"
