#!/usr/bin/env bash

fruits=(apple pear banana kiwi 'sweet mango')

echo "\$fruits: $fruits"
echo "fruits[0]: ${fruits[0]}"
echo "fruits[1]: ${fruits[1]}"
echo "fruits[2]: ${fruits[2]}"
echo "fruits[-1]: ${fruits[-1]}"

echo
echo "all fruits using * (stringify): ${fruits[*]}"

IFS=$'\n'
echo "fruits after setting IFS to newline separator"

echo "${fruits[*]}"

echo "all fruits: ${fruits[@]}"
